CREATE DATABASE FINANCE
GO

USE FINANCE
GO

CREATE TABLE CATEGORY(
    ID UNIQUEIDENTIFIER NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    COLOR VARCHAR(6) NOT NULL,
    PARENTID UNIQUEIDENTIFIER NULL
    CONSTRAINT PK_CATEGORY PRIMARY KEY(ID)
    CONSTRAINT FK_CATEGORY1 FOREIGN KEY(PARENTID) REFERENCES CATEGORY(ID)
)
GO


SELECT *
FROM CATEGORY
GO