# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  finance_domain:
    name: Finance.Domain.Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore
      run: dotnet restore .\backend\tests\Finance.Domain.Tests\Finance.Domain.Tests.csproj
    - name: Build
      run: dotnet build .\backend\tests\Finance.Domain.Tests\Finance.Domain.Tests.csproj -c Release -o.\backend\tests\Finance.Domain.Tests\release
    - name: Test
      run: dotnet test .\backend\tests\Finance.Domain.Tests\release\Finance.Domain.Tests.dll

